pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app_backend') { 
                    bat 'pip install -r requirements.txt'
                }
            }
        }

        stage('Run tests') {
            steps {
                bat 'pytest'
            }
        }

        stage('Build Docker image') {
            steps {
                bat 'docker build -t pesca-backend:latest .'
            }
        }
    }
}
